[package]
name = "migration-node-test-global-storage-includes-criterion"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }
homepage = { workspace = true }
publish = { workspace = true }
rust-version = { workspace = true }

[dependencies]
migration-node-test-types = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }


[lints]
workspace = true
