[package]
name = "mtma-node-null-core"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }
homepage = { workspace = true }
publish = { workspace = true }
rust-version = { workspace = true }

[dependencies]
serde = { workspace = true, features = ["derive"] }
clap = { workspace = true, features = ["derive"] }
anyhow = { workspace = true }
thiserror = { workspace = true }
mtma-node-types = { workspace = true }
chrono = { workspace = true }
walkdir = { workspace = true }
uuid = { workspace = true }
tracing = { workspace = true }
mtma-types = { workspace = true }

[lints]
workspace = true
