[package]
name = "mtma-migrator-test-transacting-criterion"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }
homepage = { workspace = true }
publish = { workspace = true }
rust-version = { workspace = true }

[dependencies]
mtma-migrator-test-types = { workspace = true }
anyhow = { workspace = true }
aptos-rest-client = { workspace = true }
aptos-sdk = { workspace = true }
bcs = { workspace = true }
rand = { workspace = true }
tokio = { workspace = true }

[lints]
workspace = true
