[package]
name = "mtma-node-test-types"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }
homepage = { workspace = true }
publish = { workspace = true }
rust-version = { workspace = true }

[dependencies]
thiserror = { workspace = true }
mtma-node-types = { workspace = true }
chrono = { workspace = true }
mtma-types = { workspace = true }

[lints]
workspace = true
