[package]
name = "migration-migrator-test-empty-criterion"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }
homepage = { workspace = true }
publish = { workspace = true }
rust-version = { workspace = true }

[dependencies]
migration-node-test-types = { workspace = true }


[lints]
workspace = true
