[package]
name = "mtma-migrator-pre-l1-merge-core"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }
homepage = { workspace = true }
publish = { workspace = true }
rust-version = { workspace = true }

[dependencies]
tokio = { workspace = true }
serde = { workspace = true, features = ["derive"] }
clap = { workspace = true, features = ["derive"] }
anyhow = { workspace = true }
thiserror = { workspace = true }
mtma-migrator-types = { workspace = true }
mtma-node-null-core = { workspace = true }
aptos-framework-pre-l1-merge-release = { workspace = true }
hex = { workspace = true }
mtma-types = { workspace = true }
movement-core = { workspace = true }

[lints]
workspace = true
