[package]
name = "mtma-migrator-test-types"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }
homepage = { workspace = true }
publish = { workspace = true }
rust-version = { workspace = true }

[dependencies]
mtma-node-test-types = { workspace = true }
mtma-migrator-types = { workspace = true }
serde = { workspace = true }
anyhow = { workspace = true }
hex = { workspace = true }
movement-client = { workspace = true }
aptos-rest-client = { workspace = true }
aptos-sdk = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
bcs = { workspace = true }
mtma-types = { workspace = true }

[lints]
workspace = true
