[package]
name = "migration-node-checks-sketchpad"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }
homepage = { workspace = true }
publish = { workspace = true }
rust-version = { workspace = true }

[dependencies]
migration-node-test-types = { workspace = true }
anyhow = { workspace = true }
mtma-node-null-core = { workspace = true }
migration-node-test-global-storage-injective-criterion = { workspace = true }
migration-node-test-global-storage-includes-criterion = { workspace = true }
migration-node-test-global-storage-not-empty-criterion = { workspace = true }
migration-node-preludes = { workspace = true }
tokio = { workspace = true }
chrono = { workspace = true }
rand = { workspace = true }

[dev-dependencies]
tracing-test = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true
