name: Build/Push Manifest

on:
  workflow_call:
    inputs:
      container_name:
        type: string
        description: The name of the container to build
        required: true
    secrets:
      # we need this because GITHUB_TOKEN does not have the appropriate auth to push to GHCR
      INFRA_GH_TOKEN:
        required: true
      DOCKER_HUB_USERNAME:
        required: true
      DOCKER_HUB_TOKEN:
        required: true

jobs:
  manifest-build:
    name: Build ${{ inputs.container_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with: 
          submodules: true

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.INFRA_GH_TOKEN }}
          
      - name: Login to Docker Hub for rate limiting
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push container tags
        run: |
          ./scripts/docker/build-push-manifest.sh -n ${{ inputs.container_name }}