name: Checks and Tests

on:
  push:

jobs:
  run-nix-commands:
    uses: ./.github/workflows/nix-command.yml
    strategy:
      matrix:
        command:
          # cargo checks and tests
          - cargo check --all-targets
          - cargo test
          
    with:
      command: ${{ matrix.command }}
      nix_flake_path: '.' 